public with sharing class Homework40 {
    public static void show() {

       
       
       Integer a = 20;
        Integer b = a +50;
        
        Integer i;
        
        If(i=a; i<=b; i++) {
           
            If(math.mod(i,2)==0) {
                continue; 
            }
                   System.debug(i);
              }
    

        
    }
        }
            
          

        
        

    


