public class Sport {

    public static void show(){
        
        
            
          //  Boolean flag = False;
        
          //  System.debug('I love music - ' + flag);
      
        
       // Date random = Date.newInstance(2022, 11, 14);
         //   System.debug('Appintment date is '+ random);
     
        DateTime original = DateTime.newInstance(2022, 11, 14, 12, 40, 30);
            System.debug('Entrance to building date and time is '+ original);
            
    }
}