public  virtual with sharing class EmployeeClass {
 
    String empCode;
    String empName;
    Integer salary;



    Public string getcode(){

return empCode;

    }

    public void setcode(string empCode){

        this.empCode = empCode;
    }

    public string getname(){

       return empName;
    }

    public void setname(String empName){

        this.empName = empName;
    }

    public integer getsal(){

        return salary;
    }

    public void setsal(integer salary){

        this.salary = salary;
    }


}
