public abstract with sharing class GeometryClass2 {


    public abstract void getArea();
    public abstract void getPerimeter();


    Decimal length;
    Decimal breadth;
   
    public Decimal getlength() {

        return length;

    }
    public decimal  getbreadth(){

        return breadth;
    }

    public void setlength(decimal length){
    
        this.length = length;
    }

    public void setbreadth(decimal breadth){

        this.breadth = breadth;
    }











}
