public with sharing class NewEmployeeClass  extends OldEmployeeClass{
   
   
    String designation;
    String department;


    public string getdesign(){
        return designation;
    }
    public void setdesign(String designation){

        this.designation = designation;
    }
    public string getdep(){
        return department;
    }
    public void setdep(string department){

        this.department = department;
    }
}
