public virtual with sharing class OldEmployeeClass {
   String empCode;
    String empName;
  Integer salary;

  public String getcode(){

    return empCode;
  }

  public void setcode(String empCode){

    this.empCode = empCode;
  }

  Public String getname(){
    return empName;
  }

  Public void setname(String empName){

    this.empName = empName;
  }
  public integer getsalary(){
    return salary;
  }
  public void setsalary(integer salary){

    this.salary = salary;
  }
}

