public virtual with sharing class ParentClass {
   
     Integer var1;
    String var2;
    List<Integer> list1 = new List<integer>();

    public Integer getvar1(){

        return var1;
    }

    public void setvar1(integer var1){

        this.var1 = var1;
    }

    public String getvar2(){
        return var2;
    }

    public void setvar2(string var2){

        this.var2 = var2;
    }

    public List<integer> getlist1(){

        return list1;
    }

    public void setlist1(List<integer> list1){

        this.list1 = list1;
    }


}
